### ISSUE TITLE
normal pistons behave like sticky pistons and pistons aren't able to push entities with blocks in front of them

### ISSUE THREAD

**Issue by lvasix** [WizarTheGreat/MovableTileEntities#7]
It appears that normal pistons retract entities instead of just letting them stay in the extended place. 
![screenshot-20240731-112559Z-all](https://github.com/user-attachments/assets/401f473c-4f22-4542-ab07-46fb5be52dca)
![screenshot-20240731-112618Z-all](https://github.com/user-attachments/assets/dc7fe974-d9ae-42aa-929e-0dfee4c26a5d)
Recreate by placing a normal piston, chest in front of it and then try powering/depowering the piston.

Second issue is that entities that have blocks in front of them can't be pushed
![screenshot-20240731-112737Z-all](https://github.com/user-attachments/assets/8ef21cb9-dd2d-4ada-a0f5-892546be1e60)
recreate by placing an opaque block in front of the chest and then pushing from the opaque block's side like in the image above.

I would appreciate if these got fixed as it limits options quite a lot :)

**Comment by WizarTheGreat** [comment]
Will be fixed in the next update!
(not pushing more than one block is intended, as it will not be a feature till the next update)
